service: ravi-automation-1
runtime: java
env: flex

runtime_config:
  runtime_version: 17
  operating_system: "ubuntu22"

# Remove instance_class (not supported with manual_scaling)
# instance_class: F2  # <-- REMOVE THIS

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

env_variables:
  SPRING_PROFILES_ACTIVE: gae
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root