runtime: java
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "21"

service: ravi-backend-test
beta_settings:
  cloud_sql_instances: backend-463809:us-central1:ravi

env_variables:
  SPRING_DATASOURCE_URL: jdbc:mysql://34.58.17.200:3306/test
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root
