name: GCP App Engine Deployement

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Google App Engine
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ravi-backend
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Deploy to App Engine
        run: gcloud app deploy target/ems-backend-0.0.1-SNAPSHOT.jar --quiet
